### PR TITLE
Importance of Communication

### PR DESCRIPTION
**Pull request by aclaycole**
A few notes on the importance of communication.

### CODE REVIEW

**Comment by aclaycole** [comment]
Hey @jragins @jesszliu @BenKozy @VadimChernov @lizzieBildner 
Just added some notes on the importance of communicating with the development team, what does anyone think?

Missed a flight so stranded in airport :-(

**Comment by BenKozy** [comment]
:+1: :100: :cool: :sunglasses:

**Comment by aclaycole** [comment]
Good point Vadim, thanks pal.  Will do so

**Comment by aclaycole** [comment]
thanks @VadimChernov 
just merged

**Pull request merged**
